steps:
  - label: ":construction_worker: Echo"
    command: whoami
    key: build

  - label: ":white_check_mark: Build"
    command: |
      cat Dockerfile
      pwd
      docker build .
    key: test
    depends_on: build
    
  - label: ":lock: Snyk Test"
    command: |
      docker run --rm -v $(pwd):/app -w /app snyk/snyk-cli test
    key: snyk-test
    depends_on: test
