steps:
  - label: ":construction_worker: Echo"
    command: whoami
    key: build

  - label: ":white_check_mark: Build"
    command: |
      cat Dockerfile
      pwd
      docker build -t myimage:latest .
    key: test
    depends_on: build
    
  - label: ":lock: Snyk Test"
    command: snyk test --docker myimage:latest
    key: snyk-test
    depends_on: test
